module.exports = {
    "Alteration": /(^| )alt\w*/i,
    "Fusing": /(^| )fuse\w*|(^| )fus\w*/i,
    "Alchemy": /(^| )alch\w*|(^| )alchemy\w*/i,
    "Chaos": /(^| )chaos\w*|(^| )choas\w*/i,
    "Gemcutter\'s Prism": /(^| )gemc\w*|(^| )gcp\w*/i,
    "Exalted Orb": /(^| )exa\w*|(^| )ex\w*|(^| )exalted\w*/i,
    "Chrome": /(^| )chrom\w*|(^| )chrome\w*/i,
    "Jeweller\'s Orb": /(^| )jew\w*/i,
    "Chance": /(^| )chance\w*|(^| )chanc\w*/i,
    "Cartographer\'s Chisel": /(^| )chisel\w*|(^| )cart\w*/i,
    "Scour": /(^| )scour\w*/i,
    "Blessed Orb": /(^| )blesse\w*/i,
    "Regret": /(^| )regret\w*|(^| )regr\w*/i,
    "Regal": /(^| )regal\w*|(^| )rega\w*/i,
    "Divine": /(^| )divine\w*|(^| )div\w*/i,
    "Vaal": /(^| )vaal\w*/i,
    "Wisdom Scroll": /(^| )wis\w*/i,
    "Portal Scroll": /(^| )port\w*/i,
    "Armourer\'s Scrap": /(^| )armour\w*/i,
    "Blacksmith\'s Whetstone": /(^| )blacksmith\w*|(^| )whetstone\w*/i,
    "Glassblower\'s Bauble": /(^| )glass\w*|(^| )bauble\w*/i,
    "Transmute": /(^| )tra\w*/i,
    "Augmentation": /(^| )aug\w*/i,
    "Mirror": /(^| )mir\w*|(^| )kal\w*/i
}