module.exports = {
    "Alteration": /alt/,
    "Fusing": /fuse|fus/,
    "Alchemy": /alch|alchemy/,
    "Chaos": /chaos|choas/,
    "Gemcutter\'s Prism": /gemc|gcp/,
    "Exalted Orb": /exa|ex|exalted/,
    "Chrome": /chrom|chrome/,
    "Jeweller\'s Orb": /jew/,
    "Chance": /chance|chanc/,
    "Cartographer\'s Chisel": /chisel|cart/,
    "Scour": /scour/,
    "Blessed Orb": /blesse/,
    "Regret": /regret|regr/,
    "Regal": /regal|rega/,
    "Divine": /divine|div/,
    "Vaal": /vaal/,
    "Wisdom Scroll": /wis/,
    "Portal Scroll": /port/,
    "Armourer\'s Scrap": /armour/,
    "Blacksmith\'s Whetstone": /blacksmith|whetstone/,
    "Glassblower\'s Bauble": /glass|bauble/,
    "Transmute": /tra/,
    "Augmentation": /aug/,
    "Mirror": /mir|kal/
}